AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  joke-lambda

  Sample SAM Template for joke-lambda

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  JokeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: joke_function.app.lambda_handler
      Runtime: python3.12
      Events:
        JokeAPI:
          Type: Api
          Properties:
            Path: /joke
            Method: get

Outputs:
  JokeApi:
    Description: API Gateway endpoint URL for Prod stage for Joke function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/joke/"
  JokeFunctionArn:
    Description: Joke Lambda Function ARN
    Value: !GetAtt JokeFunction.Arn
  JokeFunctionIamRole:
    Description: Implicit IAM Role created for Joke function
    Value: !GetAtt JokeFunctionRole.Arn
